- name: Copy CS9 and DS10 Puddle repo 
  copy: src=cs-ds-puddle.repo dest=/etc/yum.repos.d/cs-ds-puddle.repo
  tags: platform-ci
 
- name : Set hostname for machines Bydefault we choose pki1 for master and pki2.. for clones.
  hostname: name=pki1.example.com
  tags: platform-ci

- name : Modify hostname for master in  /etc/hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' create=yes insertafter=EOF line="{{item}} {{ansible_fqdn}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: play_hosts
  tags: platform-ci

- name : fetch file in  master in  /etc/hosts
  fetch: src=/etc/hosts dest=/etc flat=yes validate_checksum=no
  tags: platform-ci
  
- name: Install list of packages for CS Master
  yum : pkg={{item}} state=latest
  with_items:
    - redhat-pki
    - redhat-pki-console-theme
    - redhat-pki-server-theme
    - pki-console
    - 389-ds-base
    - policycoreutils-python
  tags: platform-ci

- name: Pick constants based on {{topology}}
  include_vars: "{{ item }}"
  with_items:
  - "{{ playbook_dir }}/vars/ldap_shared.yml"
  - "{{ playbook_dir }}/vars/ca_shared.yml"
  when: topology  == "topology-01"

- name: Pick constants based on {{topology}}
  include_vars: "{{ item }}"
  with_items:
  - "{{ playbook_dir }}/vars/ldap.yml"
  - "{{ playbook_dir }}/vars/ca.yml"
  - "{{ playbook_dir }}/vars/kra.yml"
  - "{{ playbook_dir }}/vars/ocsp.yml"
  - "{{ playbook_dir }}/vars/tks.yml"
  - "{{ playbook_dir }}/vars/tps.yml"
  when: topology  == "topology-02"

- name: Copying templates to /tmp folder
  copy : src=test/  dest=/tmp/
  tags: platform-ci

- name: Replace  Ldap server port in all configuration files
  replace: dest={{item}} regexp="ldapServerPort" replace={{ldapServerPort}}
  with_items:
  - /tmp/ldap.cfg
  - /tmp/ca.cfg
  - /tmp/kra.cfg
  - /tmp/ocsp.cfg
  - /tmp/tks.cfg
  - /tmp/tps.cfg
  - /tmp/ansible_constants.py
  when : topology != "topology-05"

- name: Replace  Ldap server port in all configuration files
  replace: dest={{item}} regexp="ldapServerPort" replace={{ldapServerPort}}
  with_items:
  - /tmp/ldap.cfg
  - /tmp/ca.cfg
  - /tmp/kra.cfg
  - /tmp/ocsp.cfg
  - /tmp/tks.cfg
  - /tmp/tps.cfg
  - /tmp/ansible_constants.py
  when : topology != "topology-05"

- name: Replace ServerName in all configuration files.
  replace: dest={{item}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  with_items:
  - /tmp/ldap.cfg
  - /tmp/ca.cfg
  - /tmp/kra.cfg
  - /tmp/ocsp.cfg
  - /tmp/tks.cfg
  - /tmp/tps.cfg

- name: Replace topology in use in all configuration files
  replace: dest={{item}} regexp="topology" replace={{topology}}
  with_items:
  - /tmp/ldap.cfg
  - /tmp/ca.cfg
  - /tmp/kra.cfg
  - /tmp/ocsp.cfg
  - /tmp/tks.cfg
  - /tmp/tps.cfg
  - /tmp/ansible_constants.py
