- name: Change the server.xml for OCSP port and EnableOCSP
  replace: dest=/var/lib/pki/{{ topology}}-CA/conf/server.xml regexp="9080" replace="21080"
  tags: platform-ci

- name: Change the server.xml for OCSP port and EnableOCSP
  replace: dest=/var/lib/pki/{{ topology}}-CA/conf/server.xml regexp='enableOCSP="false"' replace='enableOCSP="true"'
  tags: platform-ci

- name: Shared Secret sharing between TPS and TKS
  script: test/script {{ topology }}
  when: topology  == "topology-02" 
  tags: platform-ci
