#common to all subsystems
CLIENT_PKCS12_PASSWORD = 'Secret123'
CLIENT_DIR_PASSWORD = 'Secret123'
BACKUP_PASSWORD = 'Secret123'
CLIENT_DATABASE_PASSWORD = 'Secret123'
#CLONECA1 Instance
CLONECA1_HTTPS_PORT = '20443'
CLONECA1_HTTP_PORT = '20080'
CLONECA1_AJP_PORT = '20009'
CLONECA1_TOMCAT_PORT = '20005'
CLONECA1_CLIENT_DIR = '/opt/topology-CLONECA1'
CLONECA1_INSTANCE_NAME = 'topology-CLONECA1'
SECURITY_DOMAIN_PASSWORD = 'Secret123'
CLONECA1_PASSWORD = 'Secret123'
CLONECA1_ADMIN_USERNAME = 'caadmin'
CLONECA1_ADMIN_NICK = 'PKI CLONE CA Administrator for Example.Org'
#CLONEKRA1 Instance
CLONEKRA1_INSTANCE_NAME = 'topology-CLONEKRA1'
CLONEKRA1_HTTPS_PORT = 21443
CLONEKRA1_HTTP_PORT = 21080
CLONEKRA1_AJP_PORT = 21009
CLONEKRA1_TOMCAT_PORT = 21005
CLONEKRA1_PASSWORD = 'Secret123'
CLONEKRA1_CLIENT_DIR = '/opt/topology-CLONEKRA1'
CLONEKRA1_ADMIN_NICK = 'PKI CLONE KRA Administrator for Example.Org'
#CLONEOCSP1 Instance
CLONEOCSP1_INSTANCE_NAME = 'topology-CLONEOCSP1'
CLONEOCSP1_HTTPS_PORT = 22443
CLONEOCSP1_HTTP_PORT = 22080
CLONEOCSP1_AJP_PORT = 22009
CLONEOCSP1_TOMCAT_PORT = 22005
CLONEOCSP1_PASSWORD = 'Secret123'
CLONEOCSP1_CLIENT_DIR = '/opt/topology-CLONEOCSP1'
CLONEOCSP1_ADMIN_NICK = 'PKI CLONE OCSP Administrator for Example.Org'
