
- name: Copy CS9 and DS10 Puddle repo 
  copy: src=cs-ds-puddle.repo dest=/etc/yum.repos.d/cs-ds-puddle.repo
  tags: platform-ci
 
- name : Set hostname for machines Bydefault we choose pki1 for master and pki2.. for clones.
  hostname: name=pki1.example.com
  tags: platform-ci

- name : Modify hostname for master in  /etc/hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' create=yes insertafter=EOF line="{{item}} {{ansible_fqdn}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: play_hosts
  tags: platform-ci

- name : fetch file in  master in  /etc/hosts
  fetch: src=/etc/hosts dest=/etc flat=yes validate_checksum=no
  tags: platform-ci
  
- name: Install list of packages for CS Master
  yum : pkg={{item}} state=latest
  with_items:
    - redhat-pki
    - redhat-pki-console-theme
    - redhat-pki-server-theme
    - pki-console
    - 389-ds-base
    - policycoreutils-python
  tags: platform-cit

- name: Copying templates to /tmp folder
  copy : src=config_templates/{{topology}}/  dest=/tmp/
  tags: platform-ci

- name: Copying templates to /tmp folder
  copy : src=config_templates/ansible_constants.py  dest=/tmp/
  tags: platform-ci

- name: copy ansible_constants in /tmp
  copy: src=config_templates/ansible_constants.py  dest=/tmp/
  tags: platform-ci

- name: Get hostname and change in configuration
  replace: dest=/tmp/ansible_constants.py regexp="topology" replace={{topology}}
  tags: platform-ci

- name : fetch file in  master in  /etc/hosts
  fetch: src=/tmp/ansible_constants.py dest=/tmp flat=yes validate_checksum=no
  tags: platform-ci

- name: Get hostname and change in congiguration
  replace: dest={{var1}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  tags: platform-ci
 
- name: Setup DS Service
  shell: setup-ds.pl --silent --file={{var1}}
  tags: platform-ci

- name: Get CA server details
  replace: dest={{var2}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  tags: platform-ci

- name: Install CA master
  shell: pkispawn -s CA -f {{var2}}
  tags: platform-ci


- name: Get KRA server details
  replace: dest={{var3}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  tags: platform-ci

- name: Install KRA Master
  shell: pkispawn -s KRA -f {{var3}}
  tags: platform-ci

- name: Get  OCSP server details
  replace: dest={{var4}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  tags: platform-ci

- name: Install OCSP  master
  shell: pkispawn -s OCSP -f {{var4}}
  tags: platform-ci

- name: Get TKS  server details
  replace: dest={{var5}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  tags: platform-ci

- name: Install TKS  master
  shell: pkispawn -s TKS -f {{var5}}
  tags: platform-ci

- name: Get TPS server details
  replace: dest={{var6}} regexp="SERVERNAME" replace={{ansible_fqdn}}
  tags: platform-ci

- name: Install TPS master
  shell: pkispawn -s TPS -f {{var6}}
  tags: platform-ci

- name: Change the server.xml for OCSP port and EnableOCSP
  replace: dest=/var/lib/pki/{{ topology}}-CA/conf/server.xml regexp="9080" replace="21080"
  tags: platform-ci

- name: Change the server.xml for OCSP port and EnableOCSP
  replace: dest=/var/lib/pki/{{ topology}}-CA/conf/server.xml regexp='enableOCSP="false"' replace='enableOCSP="true"'
  tags: platform-ci

- name: Shared Secret sharing between TPS and TKS
  script: config_templates/{{topology}}/script {{ topology }}
  tags: platform-ci
